export const EVENT_PHASE = {
  DRAFT: 'DRAFT',
  REGISTRATION: 'REGISTRATION',
  CANDIDATE_REGISTRATION: 'CANDIDATE_REGISTRATION',
  VERIFICATION: 'VERIFICATION',
  ATTENDANCE: 'ATTENDANCE',
  VOTING: 'VOTING',
  FINISHED: 'FINISHED',
} as const;

export type EventPhaseType = typeof EVENT_PHASE[keyof typeof EVENT_PHASE];
