package workflow

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
	"go.uber.org/zap/zaptest"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

func (m *MockRepository) GetWorkflowByID(ctx context.Context, id string) (*Workflow, error) {
	args := m.Called(ctx, id)
	return args.Get(0).(*Workflow), args.Error(1)
}
func (m *MockRepository) GetWorkflowByName(ctx context.Context, name string) (*Workflow, error) {
	args := m.Called(ctx, name)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*Workflow), args.Error(1)
}
func (m *MockRepository) GetInitialState(ctx context.Context, workflowID string) (*WorkflowState, error) {
	args := m.Called(ctx, workflowID)
	return args.Get(0).(*WorkflowState), args.Error(1)
}
func (m *MockRepository) GetState(ctx context.Context, stateID string) (*WorkflowState, error) {
	args := m.Called(ctx, stateID)
	return args.Get(0).(*WorkflowState), args.Error(1)
}
func (m *MockRepository) GetTransition(ctx context.Context, fromStateID, toStateID string) (*WorkflowTransition, error) {
	args := m.Called(ctx, fromStateID, toStateID)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*WorkflowTransition), args.Error(1)
}
func (m *MockRepository) CreateInstance(ctx context.Context, instance *WorkflowInstance) error {
	args := m.Called(ctx, instance)
	return args.Error(0)
}
func (m *MockRepository) GetInstance(ctx context.Context, instanceID string) (*WorkflowInstance, error) {
	args := m.Called(ctx, instanceID)
	return args.Get(0).(*WorkflowInstance), args.Error(1)
}
func (m *MockRepository) GetInstanceByEntity(ctx context.Context, entityType, entityID string) (*WorkflowInstance, error) {
	args := m.Called(ctx, entityType, entityID)
	return args.Get(0).(*WorkflowInstance), args.Error(1)
}
func (m *MockRepository) UpdateInstanceAndRecordHistory(ctx context.Context, instance *WorkflowInstance, history *WorkflowHistory) error {
	args := m.Called(ctx, instance, history)
	return args.Error(0)
}

// MockRBACService is an autogenerated mock type for the AuthorizationService type
type MockRBACService struct {
	mock.Mock
}

func (m *MockRBACService) HasPermission(roleCode, permissionCode string) bool {
	args := m.Called(roleCode, permissionCode)
	return args.Bool(0)
}
func (m *MockRBACService) GetPermissionsForRole(roleCode string) []string {
	args := m.Called(roleCode)
	return args.Get(0).([]string)
}
func (m *MockRBACService) RefreshMatrix(ctx context.Context) error {
	args := m.Called(ctx)
	return args.Error(0)
}

func TestService_StartWorkflow(t *testing.T) {
	mockRepo := new(MockRepository)
	mockRBAC := new(MockRBACService)
	logger := zaptest.NewLogger(t)
	svc := NewService(mockRepo, mockRBAC, logger)

	ctx := context.Background()
	wfName := "Registration Approval"

	mockRepo.On("GetWorkflowByName", ctx, wfName).Return(&Workflow{ID: "wf1"}, nil)
	mockRepo.On("GetInitialState", ctx, "wf1").Return(&WorkflowState{ID: "st1"}, nil)
	mockRepo.On("CreateInstance", ctx, mock.Anything).Return(nil)
	mockRepo.On("UpdateInstanceAndRecordHistory", ctx, mock.Anything, mock.Anything).Return(nil)

	instance, err := svc.StartWorkflow(ctx, wfName, "registration", "reg1")
	assert.NoError(t, err)
	assert.NotNil(t, instance)
	assert.Equal(t, "st1", instance.CurrentStateID)
	mockRepo.AssertExpectations(t)
}

func TestService_TransitionState_Success(t *testing.T) {
	mockRepo := new(MockRepository)
	mockRBAC := new(MockRBACService)
	logger := zaptest.NewLogger(t)
	svc := NewService(mockRepo, mockRBAC, logger)

	ctx := context.Background()

	instance := &WorkflowInstance{ID: "inst1", CurrentStateID: "st1"}
	reqPerm := "approve.reg"
	transition := &WorkflowTransition{ID: "trans1", RequiredPermission: &reqPerm}

	mockRepo.On("GetInstance", ctx, "inst1").Return(instance, nil)
	mockRepo.On("GetTransition", ctx, "st1", "st2").Return(transition, nil)
	mockRBAC.On("HasPermission", "ADMIN", "approve.reg").Return(true)
	mockRepo.On("UpdateInstanceAndRecordHistory", ctx, mock.Anything, mock.Anything).Return(nil)

	res, err := svc.TransitionState(ctx, "inst1", "st2", "user1", "ADMIN", nil)
	assert.NoError(t, err)
	assert.Equal(t, "st2", res.CurrentStateID)
	mockRepo.AssertExpectations(t)
	mockRBAC.AssertExpectations(t)
}

func TestService_TransitionState_Unauthorized(t *testing.T) {
	mockRepo := new(MockRepository)
	mockRBAC := new(MockRBACService)
	logger := zaptest.NewLogger(t)
	svc := NewService(mockRepo, mockRBAC, logger)

	ctx := context.Background()

	instance := &WorkflowInstance{ID: "inst1", CurrentStateID: "st1"}
	reqPerm := "approve.reg"
	transition := &WorkflowTransition{ID: "trans1", RequiredPermission: &reqPerm}

	mockRepo.On("GetInstance", ctx, "inst1").Return(instance, nil)
	mockRepo.On("GetTransition", ctx, "st1", "st2").Return(transition, nil)
	mockRBAC.On("HasPermission", "GUEST", "approve.reg").Return(false)

	res, err := svc.TransitionState(ctx, "inst1", "st2", "user1", "GUEST", nil)
	assert.ErrorIs(t, err, ErrUnauthorized)
	assert.Nil(t, res)
	mockRepo.AssertExpectations(t)
	mockRBAC.AssertExpectations(t)
}

func TestService_TransitionState_InvalidTransition(t *testing.T) {
	mockRepo := new(MockRepository)
	mockRBAC := new(MockRBACService)
	logger := zaptest.NewLogger(t)
	svc := NewService(mockRepo, mockRBAC, logger)

	ctx := context.Background()
	instance := &WorkflowInstance{ID: "inst1", CurrentStateID: "st1"}

	mockRepo.On("GetInstance", ctx, "inst1").Return(instance, nil)
	mockRepo.On("GetTransition", ctx, "st1", "st2").Return((*WorkflowTransition)(nil), ErrTransitionNotAllowed)

	res, err := svc.TransitionState(ctx, "inst1", "st2", "user1", "ADMIN", nil)
	assert.ErrorIs(t, err, ErrTransitionNotAllowed)
	assert.Nil(t, res)
}
