ALTER TABLE event_settings
    ADD COLUMN IF NOT EXISTS registration_approval_mode VARCHAR(20) NOT NULL DEFAULT 'MANUAL',
    ADD COLUMN IF NOT EXISTS candidate_approval_mode VARCHAR(20) NOT NULL DEFAULT 'MANUAL',
    ADD COLUMN IF NOT EXISTS enable_attendance BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS attendance_qr_expiration INTEGER NOT NULL DEFAULT 60,
    ADD COLUMN IF NOT EXISTS attendance_radius INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS enable_voting BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS allow_revote BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS publish_final_result BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS show_candidate_list BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS show_timeline BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS show_statistics BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS show_announcements BOOLEAN NOT NULL DEFAULT false;
