CREATE SEQUENCE IF NOT EXISTS registration_number_seq START 1;

ALTER TABLE registrations 
    ADD COLUMN IF NOT EXISTS registration_number VARCHAR(100) UNIQUE,
    ADD COLUMN IF NOT EXISTS qr_token VARCHAR(255) UNIQUE,
    ADD COLUMN IF NOT EXISTS region VARCHAR(255),
    ADD COLUMN IF NOT EXISTS community VARCHAR(255),
    ADD COLUMN IF NOT EXISTS special_notes TEXT;
