-- Up
ALTER TABLE candidates DROP COLUMN IF EXISTS birth_place;
ALTER TABLE candidates DROP COLUMN IF EXISTS birth_date;
ALTER TABLE candidates DROP COLUMN IF EXISTS occupation;
ALTER TABLE candidates DROP COLUMN IF EXISTS organization;
ALTER TABLE candidates DROP COLUMN IF EXISTS address;

ALTER TABLE candidates ADD COLUMN IF NOT EXISTS company_name VARCHAR(255);
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS industrial_area VARCHAR(255);
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS job_title VARCHAR(255);
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS department VARCHAR(255);

