-- Up
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS company_name VARCHAR(255);
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS industrial_area VARCHAR(255);
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS job_title VARCHAR(255);
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS department VARCHAR(255);
